In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('wine_data.csv')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,10.62,0.38,0.41,3.0,0.072,24.8,55.7,0.99732,3.16,0.79,10.99,6,216,Bodega Pinot Classic 513,2024-10-08
216,10.21,0.17,0.60,2.5,0.059,13.7,21.2,0.99388,3.21,0.72,11.25,7,217,Castello Merlot Grand Cru 41,2024-06-03
217,11.29,0.36,0.46,2.8,0.082,26.6,40.2,0.99651,3.27,0.84,11.24,7,218,Bodega Chardonnay Grand Cru 257,2022-02-22
218,9.21,0.36,0.51,2.6,0.082,10.3,19.6,0.99854,3.20,0.70,11.09,6,219,Chateau Cabernet Special 857,2022-02-12
219,10.02,0.21,0.47,1.8,0.050,17.2,33.5,0.99676,3.04,0.70,11.37,7,220,Bodega Sauvignon Classic 591,2022-03-24

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    str
 14  date                  220 non-null    str
dtypes: float64(11), int64(2), str(2)
memory usage: 25.9 KB

In [11]:
df.date.dtype

In [14]:
df['date'] = pd.to_datetime(df['date'])

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    str
 14  date                  220 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(11), int64(2), str(1)
memory usage: 25.9 KB

In [16]:
df['month']=df.date.dt.month
df['day']=df.date.dt.day
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,month,day
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10,1,10
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15,2,15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20,3,20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25,4,25
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12,2,12

In [17]:
df['year']=df.date.dt.year
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,month,day,year
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10,1,10,2023
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15,2,15,2023
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20,3,20,2023
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25,4,25,2023
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12,2,12,2023

In [18]:
df.loc[len(df)-1]

fixed acidity                                  10.02
volatile acidity                                0.21
citric acid                                     0.47
residual sugar                                   1.8
chlorides                                       0.05
free sulfur dioxide                             17.2
total sulfur dioxide                            33.5
density                                      0.99676
pH                                              3.04
sulphates                                        0.7
alcohol                                        11.37
quality                                            7
Id                                               220
name                    Bodega Sauvignon Classic 591
date                             2022-03-24 00:00:00
month                                              3
day                                               24
year                                            2022
Name: 219, dtype: object

In [19]:
df.loc[len(df)] = [10.00,0.2,0.49,1.9,0.01,16.0,33.4,0.9918,3.00,0.1,11.0,8,220,"Old Monk", "2025-04-16", 4, 16, 2025]

In [21]:
df.shape

(221, 18)

In [24]:
df.drop(index=3, inplace=True)

In [27]:
df['high_alcohol'] = df['alcohol'] >= 10.0
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,month,day,year,high_alcohol
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,1,10,2023,True
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15 00:00:00,2,15,2023,True
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20 00:00:00,3,20,2023,True
5,8.72,0.56,0.34,0.8,0.059,22.3,59.8,0.99571,3.35,0.79,9.79,4,6,Bodega Riesling Special 559,2024-05-09 00:00:00,5,9,2024,False
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,1,14,2022,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,10.21,0.17,0.60,2.5,0.059,13.7,21.2,0.99388,3.21,0.72,11.25,7,217,Castello Merlot Grand Cru 41,2024-06-03 00:00:00,6,3,2024,True
217,11.29,0.36,0.46,2.8,0.082,26.6,40.2,0.99651,3.27,0.84,11.24,7,218,Bodega Chardonnay Grand Cru 257,2022-02-22 00:00:00,2,22,2022,True
218,9.21,0.36,0.51,2.6,0.082,10.3,19.6,0.99854,3.20,0.70,11.09,6,219,Chateau Cabernet Special 857,2022-02-12 00:00:00,2,12,2022,True
219,10.02,0.21,0.47,1.8,0.050,17.2,33.5,0.99676,3.04,0.70,11.37,7,220,Bodega Sauvignon Classic 591,2022-03-24 00:00:00,3,24,2022,True
220,10.00,0.20,0.49,1.9,0.010,16.0,33.4,0.99180,3.00,0.10,11.00,8,220,Old Monk,2025-04-16,4,16,2025,True

In [28]:
df['wine_type'] = 'Red Wine'
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,month,day,year,high_alcohol,wine_type
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,1,10,2023,True,Red Wine
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15 00:00:00,2,15,2023,True,Red Wine
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20 00:00:00,3,20,2023,True,Red Wine
5,8.72,0.56,0.34,0.8,0.059,22.3,59.8,0.99571,3.35,0.79,9.79,4,6,Bodega Riesling Special 559,2024-05-09 00:00:00,5,9,2024,False,Red Wine
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,1,14,2022,False,Red Wine

In [29]:
data1 = {
    'name': ['A', 'B', 'C'],
    'age': [22,44,66],
    'salary': [50000, 60000, 70000]
}

data2 = {
    'name': ['D', 'E', 'F'],
    'age': [33,55,77],
    'salary': [80000, 90000, 100000]
}

In [30]:
new_df1 = pd.DataFrame(data1)
new_df2 = pd.DataFrame(data2)

In [31]:
new_df2.head()

  name  age  salary
0    D   33   80000
1    E   55   90000
2    F   77  100000

In [37]:
new_df = pd.concat([new_df1, new_df2], ignore_index=True, axis = 0)
new_df

  name  age  salary
0    A   22   50000
1    B   44   60000
2    C   66   70000
3    D   33   80000
4    E   55   90000
5    F   77  100000

In [38]:
import numpy as np